# Generated by Django 2.2.4 on 2020-01-09 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0002_book'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='title',
            new_name='store_path',
        ),
        migrations.RemoveField(
            model_name='book',
            name='title_2',
        ),
        migrations.AddField(
            model_name='book',
            name='readyness',
            field=models.CharField(default='1', max_length=4),
            preserve_default=False,
        ),
    ]
