# Generated by Django 2.2.4 on 2020-01-09 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0006_imageupload'),
    ]

    operations = [
        migrations.AddField(
            model_name='imageupload',
            name='readyness',
            field=models.CharField(default='0', max_length=1),
        ),
        migrations.AddField(
            model_name='imageupload',
            name='result_file',
            field=models.TextField(default='temp'),
            preserve_default=False,
        ),
    ]
