# Generated by Django 2.2.4 on 2020-01-09 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0007_auto_20200109_1630'),
    ]

    operations = [
        migrations.RenameField(
            model_name='album',
            old_name='readyness',
            new_name='readiness',
        ),
        migrations.RenameField(
            model_name='imageupload',
            old_name='readyness',
            new_name='readiness',
        ),
    ]
