# Generated by Django 2.2.4 on 2020-01-10 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0009_imageupload_result_file2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imageupload',
            name='result_file2',
        ),
        migrations.AlterField(
            model_name='imageupload',
            name='result_file',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
