# Generated by Django 2.2.4 on 2020-01-10 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0010_auto_20200110_1350'),
    ]

    operations = [
        migrations.AddField(
            model_name='imageupload',
            name='deeplab_file',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='imageupload',
            name='mask_file',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='imageupload',
            name='trimap_file',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
